# J-Link Remote tunnel relay server v7 — dual mode (SN and SN+password)
#
# Wire protocol (compatible with SEGGER J-Link Remote Server):
#
# Simple path (S/N, no password):
#   Remote: "44332211"|SN(le32)  -> i32 status (0=OK)  -> FWPROT announce ...
#   Client: "88776655"|SN(le32)  -> i32 status (0=OK)  <- announce, then relay
#
# TLV path (password and/or name):
#   Remote: ver(le32)=0x00271099 -> ver echo -> TLV tokens -> i32 0
#           -> keepalive 5x(0xAA|TS) @1s -> 0xB6|TS
#           -> 8B random challenge -> waits 32B SHA-256 response
#   Client: login(le32)=0x002710AA -> i32 0 -> TLV tokens -> i32 0
#           -> 8B challenge (relayed from remote) -> 32B SHA256(chal||pw)
#           -> i32 0 -> announce -> relay
#   TLV token stream: raw u32 LE words; string bytes inline; ends ...FFFFFFFF 00000000
#   Auth is client<->remote end-to-end; the tunnel server only relays 8B/32B.
import asyncio
import logging
import struct
import sys
import time

MAGIC_REMOTE = b"\x44\x33\x22\x11"
MAGIC_CLIENT = b"\x88\x77\x66\x55"
VER_REMOTE = b"\x99\x10\x27\x00"    # 0x00271099 remote TLV hello
LOGIN_CLIENT = b"\xaa\x10\x27\x00"  # 0x002710AA client login

log = logging.getLogger("tunnel")


def hexd(tag: str, data: bytes) -> str:
    asc = "".join(chr(c) if 32 <= c < 127 else "." for c in data)
    return f"{tag} len={len(data)} {data.hex()} |{asc}|"


async def read_tlv_stream(reader) -> dict:
    """Parse the TLV token stream (BYTE-oriented; name strings make it
    unaligned, so this must not read fixed u32 words).

    Token grammar:
      0x00000000              no-name marker (no value)
      0x00000001 len bytes    name identifier
      0x00000002 u32          password flag
      0x00000003 u32          version-gated item
      0x00000004 u32          S/N identifier
      0xFFFFFFFF 0x00000000   end of stream
    Returns {"name": str|None, "sn": int|None, "pw": int|None}.
    """
    res = {"name": None, "sn": None, "pw": None}
    while True:
        t = struct.unpack("<I", await reader.readexactly(4))[0]
        if t == 0xFFFFFFFF:
            await reader.readexactly(4)  # trailing zero word
            return res
        if t == 1:
            n = struct.unpack("<I", await reader.readexactly(4))[0]
            res["name"] = (await reader.readexactly(n)).decode("latin1")
        elif t in (2, 3, 4):
            v = struct.unpack("<I", await reader.readexactly(4))[0]
            if t == 2:
                res["pw"] = v
            elif t == 4:
                res["sn"] = v
        # t == 0: marker without value; unknown types: skipped (4-byte value assumed)


class Entry:
    def __init__(self):
        self.lock = asyncio.Lock()
        self.buffer = []           # remote bytes before pairing (announce)
        self.client = None         # client StreamWriter when paired
        self.remote_writer = None
        self.challenge = None      # 8B auth challenge generated by the remote
        self.challenge_evt = asyncio.Event()
        self.stats = {"c2r": 0, "r2c": 0}
        self.t_pair = None


class Registry:
    def __init__(self):
        self.remotes = {}

    def register(self, sn, entry):
        old = self.remotes.get(sn)
        self.remotes[sn] = entry
        return old

    def lookup(self, sn):
        return self.remotes.get(sn)

    def remove(self, sn, entry):
        if self.remotes.get(sn) is entry:
            del self.remotes[sn]


async def keepalive_task(writer: asyncio.StreamWriter):
    """Keepalive sequence: 5x 0xAA|TS @1s then 0xB6|TS."""
    try:
        for _ in range(5):
            writer.write(b"\xaa" + struct.pack("<I", int(time.time())))
            await writer.drain()
            await asyncio.sleep(1.0)
        writer.write(b"\xb6" + struct.pack("<I", int(time.time())))
        await writer.drain()
        log.debug("keepalive sequence complete")
    except Exception:
        pass


async def remote_side(reader, writer, entry: Entry, sn, tlv: bool, has_auth: bool = False):
    # Single owner of the remote socket read side.
    ka = None
    try:
        if tlv and has_auth:
            # password mode: the remote sends its 8B auth challenge right after
            # keepalive and THEN its announce while waiting for the client's
            # 32B response — so after capturing the challenge we must NOT read
            # anything here; the response is written to the remote socket by
            # the client coroutine and consumed by the remote exe itself.
            # (no-password TLV mode sends the announce directly — no challenge)
            chal = await asyncio.wait_for(reader.readexactly(8), timeout=30)
            async with entry.lock:
                entry.challenge = chal
                entry.challenge_evt.set()
            log.info(f"remote SN={sn} auth challenge {chal.hex()}")

        while True:
            data = await reader.read(65536)
            if not data:
                log.info(f"remote SN={sn} EOF")
                break
            async with entry.lock:
                cw = entry.client
                if cw is None:
                    entry.buffer.append(data)
                    log.debug(hexd(f"SN{sn} pre-pair", data))
                else:
                    entry.stats["r2c"] += len(data)
                    log.debug(hexd(f"SN{sn} R->C", data))
                    cw.write(data)
                    await cw.drain()
    except Exception as e:
        log.debug(f"remote SN={sn} read loop end: {e}")
    finally:
        if ka:
            ka.cancel()
    async with entry.lock:
        cw = entry.client
        entry.client = None
    if cw is not None:
        try:
            cw.close()
        except Exception:
            pass
        dur = time.time() - (entry.t_pair or time.time())
        log.info(f"session SN={sn} closed: c2r={entry.stats['c2r']}B r2c={entry.stats['r2c']}B {dur:.1f}s")
    try:
        writer.close()
    except Exception:
        pass



async def reject_duplicate(reg, key, writer, n) -> bool:
    """True if a live entry already holds the key -> reply -3 (duplicate
    registration, per SEGGER status semantics) and keep the incumbent."""
    old = reg.lookup(key)
    if old is None:
        return False
    log.warning(f"conn {n}: duplicate registration for key={key} -> reject (-3)")
    writer.write(struct.pack("<i", -3))
    await writer.drain()
    writer.close()
    return True


async def handle(reader, writer, reg: Registry):
    n = getattr(handle, "_n", 0) + 1
    handle._n = n
    peer = writer.get_extra_info("peername")
    try:
        head = await asyncio.wait_for(reader.readexactly(4), timeout=60)
    except Exception as e:
        log.warning(f"conn {n}: handshake read failed: {e}")
        writer.close()
        return

    if head in (MAGIC_REMOTE[:4], MAGIC_CLIENT[:4]):
        head += await reader.readexactly(4)
    magic, sn = head[:4], None
    if len(head) >= 8:
        sn = struct.unpack("<I", head[4:8])[0]
    log.info(f"conn {n} from {peer} magic={magic.hex()} SN={sn}")

    if magic == MAGIC_REMOTE:
        if await reject_duplicate(reg, sn, writer, n):
            return
        entry = Entry()
        entry.remote_writer = writer
        reg.register(sn, entry)
        writer.write(struct.pack("<i", 0))
        await writer.drain()
        log.info(f"remote registered SN={sn} (simple path)")
        await remote_side(reader, writer, entry, sn, tlv=False)
        reg.remove(sn, entry)
        return

    if head == VER_REMOTE:
        # TLV-path remote registration; identity (name and/or SN) in TLV tokens
        entry = Entry()
        entry.remote_writer = writer
        writer.write(VER_REMOTE)  # server version echo
        await writer.drain()
        try:
            ident = await asyncio.wait_for(read_tlv_stream(reader), timeout=15)
        except Exception as e:
            log.warning(f"conn {n}: TLV read failed: {e}")
            writer.close()
            return
        key = f"n:{ident['name']}" if ident["name"] else f"s:{ident['sn']}"
        log.info(f"conn {n} TLV remote: {ident} -> key={key}")
        if await reject_duplicate(reg, key, writer, n):
            return
        reg.register(key, entry)
        writer.write(struct.pack("<i", 0))  # TLV status OK
        await writer.drain()
        log.info(f"remote registered key={key} (TLV path)")
        ka = asyncio.create_task(keepalive_task(writer))
        entry.sn_label = ident["name"] or ident["sn"]
        await remote_side(reader, writer, entry, entry.sn_label, tlv=True, has_auth=(ident["pw"] is not None))
        reg.remove(key, entry)
        return

    if magic == MAGIC_CLIENT:
        entry = reg.lookup(sn)
        if entry is None:
            log.warning(f"conn {n}: no remote for SN={sn} -> reject (-2)")
            writer.write(struct.pack("<i", -2))
            await writer.drain()
            writer.close()
            return
        async with entry.lock:
            busy = entry.client is not None
        if busy:
            log.warning(f"conn {n}: SN={sn} busy -> reject (-4)")
            writer.write(struct.pack("<i", -4))
            await writer.drain()
            writer.close()
            return
        writer.write(struct.pack("<i", 0))
        await writer.drain()
        log.info(f"client paired with remote SN={sn} (simple path)")
        entry.t_pair = time.time()
        async with entry.lock:
            entry.client = writer
            try:
                for chunk in entry.buffer:
                    log.debug(hexd(f"SN{sn} flush R->C", chunk))
                    writer.write(chunk)
                entry.stats["r2c"] += sum(len(c) for c in entry.buffer)
                entry.buffer.clear()
                await writer.drain()
            except Exception as e:
                log.warning(f"flush failed: {e}")
        await client_relay(reader, writer, entry, sn)
        return

    if head == LOGIN_CLIENT:
        # TLV-path client; identity (name and/or SN) in TLV tokens
        writer.write(struct.pack("<i", 0))  # login ack
        await writer.drain()
        try:
            ident = await asyncio.wait_for(read_tlv_stream(reader), timeout=15)
        except Exception as e:
            log.warning(f"conn {n}: client TLV read failed: {e}")
            writer.close()
            return
        key = f"n:{ident['name']}" if ident["name"] else f"s:{ident['sn']}"
        sn = ident["name"] or ident["sn"]
        log.info(f"conn {n} TLV client: {ident} -> key={key}")
        entry = reg.lookup(key)
        if entry is None:
            log.warning(f"conn {n}: no remote for key={key} -> reject (-2)")
            writer.write(struct.pack("<i", -2))
            await writer.drain()
            writer.close()
            return
        async with entry.lock:
            busy = entry.client is not None
        if busy:
            log.warning(f"conn {n}: key={key} busy -> reject (-4)")
            writer.write(struct.pack("<i", -4))
            await writer.drain()
            writer.close()
            return
        writer.write(struct.pack("<i", 0))  # TLV status OK
        await writer.drain()
        if ident["pw"] is not None:
            # password mode: wait for the remote's 8B challenge (it may still
            # be in keepalive)
            try:
                await asyncio.wait_for(entry.challenge_evt.wait(), timeout=20)
            except asyncio.TimeoutError:
                log.warning(f"conn {n}: challenge never arrived for key={key}")
                writer.close()
                return
            writer.write(entry.challenge)
            await writer.drain()
            log.info(f"client key={key} got challenge {entry.challenge.hex()}")
            resp = await asyncio.wait_for(reader.readexactly(0x20), timeout=20)
            log.info(f"client key={key} auth response {resp.hex()}")
            # relay response to the remote (the remote exe consumes it and then
            # sends its announce; the client reads the announce right after its
            # response with NO intermediate status — do not send anything here)
            try:
                entry.remote_writer.write(resp)
                await entry.remote_writer.drain()
            except Exception as e:
                log.warning(f"response relay failed: {e}")
        entry.t_pair = time.time()
        async with entry.lock:
            entry.client = writer
            try:
                for chunk in entry.buffer:
                    log.debug(hexd(f"SN{sn} flush R->C", chunk))
                    writer.write(chunk)
                entry.stats["r2c"] += sum(len(c) for c in entry.buffer)
                entry.buffer.clear()
                await writer.drain()
            except Exception as e:
                log.warning(f"flush failed: {e}")
        log.info(f"client paired with remote SN={sn} (TLV path)")
        await client_relay(reader, writer, entry, sn)
        return

    log.warning(f"conn {n}: unknown magic {magic.hex()} -> close")
    writer.close()


async def client_relay(reader, writer, entry: Entry, sn):
    stats = {"n": 0}
    try:
        while True:
            data = await reader.read(65536)
            if not data:
                break
            stats["n"] += len(data)
            log.debug(hexd(f"SN{sn} C->R", data))
            entry.remote_writer.write(data)
            await entry.remote_writer.drain()
    except Exception as e:
        log.debug(f"client read loop end: {e}")
    entry.stats["c2r"] += stats["n"]
    log.info(f"client SN={sn} disconnected ({stats['n']}B sent)")
    async with entry.lock:
        entry.client = None
    try:
        entry.remote_writer.close()
    except Exception:
        pass
    writer.close()


async def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 19020
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )
    reg = Registry()
    srv = await asyncio.start_server(lambda r, w: handle(r, w, reg), "0.0.0.0", port)
    log.info(f"tunnel server v7 (dual mode) listening on :{port}")
    async with srv:
        await srv.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
